// Re-export all services from a single entry point
export * from './firebase'
export * as ClientService from './client.service'
export * as TablesService from './tables.service'
export * as MenuService from './menu.service'
export * as UsersService from './users.service'
export * as PostsService from './posts.service'
export * as OrdersService from './orders.service'
export * as ReservationsService from './reservations.service'
export * as FilesService from './files.service'
